name: CI/CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        name: upload site to host 

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Upload Files
              id: upload
              uses: Creepios/sftp-action@v1.0.3
              with:
                server: ${{ secrets.ftp_host }}:2022
                local-dir: ./webroot/
                host: ${{ secrets.ftp_host}}
                port: 2022
                username: 'git.66991d99'
                password: ${{ secrets.ftp_password }}
                localPath: './site/'
                remotePath: './webroot/'
              env:
                 user_name: "github-actions[bot]"
                  user_email: "github-actions[bot]@users.noreply.github.com" 
